CREATE TABLE IF NOT EXISTS TurnstileEvents (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   ticketId INTEGER NOT NULL,
   time TIMESTAMP NOT NULL,
   action VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS TicketEvents (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    ticketId INTEGER NOT NULL,
    time TIMESTAMP NOT NULL,
    expirationTime TIMESTAMP NOT NULL,
    action VARCHAR(6) NOT NULL
);
